### ISSUE TITLE
Improve styles on the administration.

### ISSUE THREAD

**Issue by rozay** [Karamfil4etata/HappyMe#36]
- [x] Override the existing theme to match our design palette;
- [x] Include fonts;
- [x] Make the administration sidebar selectable;
- [ ] Style the administration editor views

**Comment by rozay** [comment]
https://github.com/Karamfil4etata/HappyMe/commit/7efbb74f0c5152d5b6314ba4223e550ce0e41da6

**Comment by mhristoforova** [comment]
@rozay yey

**Comment by Teodor92** [comment]
This should be split into separate tasks.
