### ISSUE TITLE
Landing page - slider issues

### ISSUE THREAD

**Issue by YanaSlavcheva** [Karamfil4etata/HappyMe#75]
- dots under the scroller are too damn small
- maybe we shall put opinions there instead of facts for autism (Bobi, Nadya)
- Maybe we shall use a blurred picture as background? This way it looks as a draft to me
- every slide has different height

**Comment by rozay** [comment]
https://github.com/Karamfil4etata/HappyMe/commit/92f00e060ce749eec472b91293d9d6d1a1e19dce
