### ISSUE TITLE
Create FB post for Beta Launch (Alphabet module) 

### ISSUE THREAD

**Issue by YanaSlavcheva** [Karamfil4etata/HappyMe#84]
- [x] Create image 4 post
- [ ] Create content 4 post
- [ ] Laubch post

**Comment by mhristoforova** [comment]
![facebookpost-alphabet](https://cloud.githubusercontent.com/assets/15387719/16899772/9057f0c6-4c18-11e6-8390-3729f3313c9f.png)

**Comment by YanaSlavcheva** [comment]
Done
